### ISSUE TITLE
Adding click type condition when executing an action

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#15]
**User story:** As a configurator, I want to differenciate the type of click to execute an action when a player clicks on an item to be able to add different behaviors on a same item.

**Features:**

In the configuration, an action may have the property `click-types` which takes the following values in a list: `LEFT`, `RIGHT`, `MIDDLE`, `ALL`. When the property is not defined, it takes the value `ALL` by default. The `ALL` value is set to handle all types of clicks.

**Examples:**
```yaml
message:
  type: "MESSAGE"
  click-types: 
    - "LEFT"
    - "RIGHT"
  message: "This is a message"
```
```yaml
message:
  type: "MESSAGE"
  message: "This is a message"
```
When a player clicks on the item, only actions which match the type of its click will be executed.

If the `ALL` click type is set in combination with other click types, it overrides them all.
