### ISSUE TITLE
Improving existing actions

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#16]
**User story:** As a configurator, I want to configure some existing item actions more easily.

**Actions:**

1. Player command

Replacing single command by a list of commands.

```yaml
# Make the player execute a list of commands.
player-command:
  type: "PLAYER_COMMAND"
  # List of commands to execute without slash.
  # Supported placeholders:
  # - %player_name%: Name of the player who executes the action.
  # - %player_uuid%: UUID of the player who executes the action.
  commands: 
    - "command_1"
    - "command 2 arg1"
    - "command 3 arg1 arg2 arg3"
```

2. Console command

Renaming `SERVER_COMMAND` to `CONSOLE_COMMAND` and replacing single command by a list of commands.

```yaml
# Make the console execute a list of commands.
player-command:
  type: "CONSOLE_COMMAND"
  # List of commands to execute without slash.
  # Supported placeholders:
  # - %player_name%: Name of the player who executes the action.
  # - %player_uuid%: UUID of the player who executes the action.
  commands: 
    - "command_1"
    - "command 2 arg1"
    - "command 3 arg1 arg2 arg3"
```

3. Message

Replacing single message by a list of messages.

```yaml
# Send messages to the player.
message:
  type: "MESSAGE"
  # List of messages to send.
  # Features supported:
  # - Placeholders
  # - Color codes prefixed by the character '&' (ex: &e)
  # - Hexadecimal color codes prefixed by the character '#' (ex: #FFFFFF)
  messages: 
    - "message 1"
    - "message 2"
    - "message 3"
```
