### ISSUE TITLE
Adding new actions

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#17]
**User story:** As a configurator, I want to have more available actions to customize my items' behavior.

**New actions:**

1. Sound

**Feature:** Play a sound when a player clicks on an item.

**Configuration:**
```yaml
# Play a sound to the player who is clicking on the item.
sound:
  type: "SOUND"
  # Sound name to play.
  sound: "<name>"
  # How far the sound can be heard.
  volume: <float>
  # How fast the sound is played.
  pitch: <float>
```
> Note: [XSeries](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XSound.java) seems to be an interesting library to handle sounds. Howerver, there is no need for retro compatibility for now, so Bukkit sounds will be used instead.

2. Broadcast

**Feature:** Broadcast a message in the chat when a player clicks on the item.

**Configuration:**
```yaml
# Broadcast messages in the chat.
broadcast:
  type: "BROADCAST"
  # List of messages to broadcast.
  # Features supported:
  # - Placeholders
  # - Color codes prefixed by the character '&' (ex: &e)
  # - Hexadecimal color codes prefixed by the character '#' (ex: #FFFFFF)
  messages:
    - "message 1"
    - "message 2"
    - "message 3"
```
