### ISSUE TITLE
Add action to update items

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#23]
**User Story:** As a configurator, I want to be able to update the content of an inventory to display dyanmic information.

## Update content

This feature will be implemented as an item action.

```yaml
# Update the content of an opened inventory.
update-content:
  type: "UPDATE_CONTENT"
```

## Update paginations

This feature will be implemented as an item action.

```yaml
# Update paginations in an opened inventory.
update-paginations:
  type: "UPDATE_PAGINATIONS"
  # The ids of the paginations to update.
  pagination-ids:
    - <pagination-id-1>
    - <pagination-id-2>
    - <pagination-id-3>
```
