### ISSUE TITLE
Add action to update the inventory model

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#25]
~**User Story:** As a configurator, I would like to modify the state of an inventory when a player clicks on an item to be able to build dynamic inventories.~

## ~Feature~

~This feature will be implemented as an item action with the following configuration:~
```yaml
# Update the inventory state by changing the value of a property.
update-state:
  type: "UPDATE_STATE"
  # The name in uppercase of the property to update.
  # You can set anything you want, even a property that is not provided by the code.
  property-name: "<name>"
  # The value of the property. By default, it will override the current value by the one below.
  # Only the following types are supported: string, int, double, boolean.
  # For numbers such as int and double, you can prefix the value by the symbols '+' and '-' to
  # make an addition / subtraction instead of replacing the current value by the new one.
  property-value: <value>
```
## ~Placeholders~

~All the properties should be available as placeholders by default without needing to declare and registering a new placeholder manually for each of them in the inventory provider.~
