### ISSUE TITLE
Inventory history

### ISSUE THREAD

**Issue by Syr0ws** [Syr0ws/FastInventory#26]
**User Story:** As a user, I want to be able to go backward / foward to previously opened inventories like in browsers to be able to navigate more easily.

## Inventory history

To implement this feature, we will introduce the concept of inventory history. An inventory history is a structure, more precisely a chain, that contains all the inventories in the order they were opened.

Each opened inventory belongs to an history in which it may be the **root** or a **child**.

## Actions

This feature will come with new item actions. The behavior of each new action is described in the scheme below.

![History Actions Scheme](https://github.com/user-attachments/assets/f6f7f459-32c1-4a9b-a08c-137b6566a8b5)

### Backward

```yaml
# Open a previously opened inventory in the history which is before the current one in the history.
backward:
  # The action type.
  type: "BACKWARD"
  # This property is optional. When set, the action opens the previously opened inventory before the current
  # one which has the specified id. When not set, the inventory just before the current one in the history is opened.
  inventory-id: ""
```
> Note: When there is no inventory with the specified id in the history or the current inventory is the root of the history, the action does no do anything.

### Forward

```yaml
# Open a previously opened inventory in the history which is after the current one in the history.
forward:
  # The action type.
  type: "FORWARD"
  # This property is optional. When set, the action opens the previously opened inventory after the current
  # one which has the specified id. When not set, the inventory just after the current one in the history is opened.
  inventory-id: ""
```
> Note: When there is no inventory with the specified id in the history or the current inventory is the root of the history, the action does no do anything.

### Home

```yaml
# Open the root inventory in the history.
home:
  # The action type.
  type: "HOME"
```
> Note: If the current inventory is already the root inventory, the action does not do anything.

### Open inventory

```yaml
# Open an inventory.
open-inventory:
  # The action type.
  type: "OPEN_INVENTORY"
  # The id of the inventory to open.
  inventory-id: "<id>"
  # If true, a new history will be created for the inventory.
  # If false, the inventory will be appended at the end of it. 
  new-history: <true|false>
```

## Impact analysis

This feature will introduce breaking changes in the way inventories are opened.
